### ISSUE TITLE
Repos are empty?

### ISSUE THREAD

**Issue by Aersaud** [PhasecoreX/docker-red-discordbot#1]
Hello,

I am using your image and enjoying it thus far...however I ran into a problem trying to add a repo and installing a cog from that repo. When adding the repo, the bot sees it as empty. 

An example (I use $ to signal the bot)

**Me:** $repo add Laggrons-Dumb-Cogs https://github.com/retke/Laggrons-Dumb-Cogs
**Bot:** (Third party info here)
**Me:** 'I agree'
**Bot:** Repo Laggrons-Dumb-Cogs successfully added.
**Me:** $cog install Laggrons-Dumb-Cogs say
**Bot:** Error: there is no cog by the name of say in the Laggrons-Dumb-Cogs repo.

Here is my docker-compose.yml

```
version: '3'
services:
    start-redbot.sh:
        container_name: 'red_discord'
        volumes:
            - '/home/[redacted]/docker/red:/data'
        restart: 'no'
        environment:
            - TZ=America/New_York
            - PGID=1000
            - PUID=1000
        image: phasecorex/red-discordbot
```

Everything else works fine and I can load the default modules properly.

`ls -la `shows that I own all the folders in the directory I am mounting as a volume. I can actually see the repo and the files it clones when I go into the directory and the container.
