### ISSUE TITLE
Cannot start Python virtual environment

### ISSUE THREAD

**Issue by JareBear124** [PhasecoreX/docker-red-discordbot#102]
**Describe the bug**
When starting the container, the Python virtual environment never seems to be able to run. The Portainer log is shown below.
```
Timezone set to Etc/UTC
Starting with UID/GID: 1000/1000
Activating Python virtual environment...
Error: Command '['/data/venv/bin/python', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
This issue did not start until I restarting the container. I have tried deleting the venv folder and re-pulling the image, but the issue still persists.

**Docker Compose**
```
version: "3.2"
services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - /home/jarebear124/docker-configs/redbot:/data
    environment:
      - TOKEN=###
      - PREFIX=!
      - TZ=Etc/UTC
      - PUID=1000
```

**Environment info:**
Docker compose is run from Portainer with Linux-based docker. 
Ubuntu 22.04.4 LTS
GNOME Version 42.9
