### ISSUE TITLE
Python unable to install cog requirments.

### ISSUE THREAD

**Issue by Hackatoan** [PhasecoreX/docker-red-discordbot#109]
**Describe the bug**

unable to load any python requirements when loading cogs.

**Run command**
```
version: "3.2"
services:
  redbot:
    container_name: ginobot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - ./redbot:/data
    environment:
      - TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - PREFIX=.
      - TZ=America/Los_Angeles
      - PUID=1000
```

**Environment info:**
Ubuntu VM running through proxmox

**Additional context**

after restarting and deleting venv folder
`
Error: Command '['/data/venv/bin/python', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
`

error i got when trying to install a cog.
`
[2025-02-08 16:13:22] [ERROR] red.downloader: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/venv/lib/python3.11/site-packages/pip/__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 11, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/build_env.py", line 18, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/data/venv/lib/python3.11/site-packages/pip/_internal/utils/logging.py", line 22, in <module>
    from pip._vendor.rich.logging import RichHandler
  File "/data/venv/lib/python3.11/site-packages/pip/_vendor/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/data/venv/lib/python3.11/site-packages/pip/_vendor/rich/traceback.py", line 22, in <module>
    from pip._vendor.pygments.lexers import guess_lexer_for_filename
  File "/data/venv/lib/python3.11/site-packages/pip/_vendor/pygments/lexers/__init__.py", line 19, in <module>
    from pip._vendor.pygments.plugin import find_plugin_lexers
  File "/data/venv/lib/python3.11/site-packages/pip/_vendor/pygments/plugin.py", line 35, in <module>
    from importlib.metadata import entry_points
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 6, in <module>
    import email
SyntaxError: source code string cannot contain null bytes
[2025-02-08 16:13:22] [ERROR] red.downloader: Something went wrong when installing the following requirements: yt-dlp

`
