### ISSUE TITLE
I can ping the bot, but all other command get empty responses

### ISSUE THREAD

**Issue by sangdth** [PhasecoreX/docker-red-discordbot#113]
Hi, thanks for the works.

I'm trying to install but stuck at making it doing simple tasks following the guidelines.

For example, I can `!ping` and got the `Pong` response. But everything else just get empty.

I gave the bot all the intents and as many permissions as possible, even `Admin`, but the issue stays.

I included the extra arg `--debug` but nothing strange show up, please check the screenshot to see. I typed the commands and check logs at the same time.

I'm running the compose on a VPS (controlled via Dokploy.)

```
services:
  redbot:
    image: phasecorex/red-discordbot
    restart: unless-stopped
    environment:
      - TOKEN=${DISCORD_BOT_TOKEN}
      - PREFIX=!
      - TZ=Europe/Helsinki
      - PUID=1000
      - EXTRA_ARGS=--debug
    volumes:
      - redbot_data:/data

volumes:
  redbot_data:
```

![Image](https://github.com/user-attachments/assets/b321d229-0c9e-40dd-8b2c-c25b5d7cf712)
