### ISSUE TITLE
Current Docker tag "audio" broken

### ISSUE THREAD

**Issue by simonmicro** [PhasecoreX/docker-red-discordbot#47]
**Describe the bug**
Venv can not be activated:
```
Attaching to redbot_redbot_1
redbot_1  | 2022-01-22T00:11:48.787698337Z Timezone set to Europe/Berlin
redbot_1  | 2022-01-22T00:11:48.837502906Z Niceness set to -20
redbot_1  | 2022-01-22T00:11:48.853955392Z Starting with UID/GID: 1000/1000
redbot_1  | 2022-01-22T00:11:48.857068121Z Activating Python virtual environment...
redbot_1  | 2022-01-22T00:11:49.595057062Z Error: Command '['/data/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.                                                                     
redbot_1  | 2022-01-22T00:11:51.620614202Z Timezone set to Europe/Berlin
redbot_1  | 2022-01-22T00:11:51.663316141Z Niceness set to -20
redbot_1  | 2022-01-22T00:11:51.663832324Z Starting with UID/GID: 1000/1000
redbot_1  | 2022-01-22T00:11:51.682208809Z Activating Python virtual environment...
redbot_1  | 2022-01-22T00:11:52.497792902Z Error: Command '['/data/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.                                                                     
redbot_1  | 2022-01-22T00:11:54.384732837Z Timezone set to Europe/Berlin
redbot_1  | 2022-01-22T00:11:54.428003080Z Niceness set to -20
redbot_1  | 2022-01-22T00:11:54.428745138Z Starting with UID/GID: 1000/1000
redbot_1  | 2022-01-22T00:11:54.452191262Z Activating Python virtual environment...
redbot_1  | 2022-01-22T00:11:55.200290532Z Error: Command '['/data/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Run command**
```
version: "3.2"
services:
    redbot:
        image: ghcr.io/phasecorex/red-discordbot:audio
        restart: always
        volumes:
            - ./redbot:/data
        environment:
            - TOKEN=****************
            - PREFIX=!
            - TZ=Europe/Berlin
            - PUID=1000
            - NICENESS=-20
        cap_add:
            - SYS_NICE
```

**Environment info:**
Irrelevant.

**Additional context**
Idk the exact reason, just that the current docker image won't boot...
