### ISSUE TITLE
New repo permissions incorrect

### ISSUE THREAD

**Issue by JzJad** [PhasecoreX/docker-red-discordbot#62]
**Describe the bug**
Upon adding a new repo, the folder under cogs is created with root:root instead of the expected 1000:1000, making the repo unusable. Fixing the permissions and restarting the bot then allows for cogs to be installed without further issue.

**Run command**
```
version: "3.2"
services:
  nexus:
    container_name: nexus-bot
    image: phasecorex/red-discordbot:full
    restart: unless-stopped
    volumes:
      - /mnt/docker/nexus-bot/data:/data
    environment:
      - TOKEN=************
      - PREFIX=.
      - TZ=America/Chicago
      - PUID=1000
      - OWNER=************
```

**Environment info:**
AMD64
