### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by masiv1001** [PhasecoreX/docker-red-discordbot#75]
**Describe the bug**
Some commands don't work (don't give any output), doing [p]help does work, so does [p]uptime but [p]cogs nor [p]listdisabled do

**Run command**
```
version: "3.3"
services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot:full
    restart: unless-stopped
    volumes:
      - [R]/redbot:/data
    environment:
      - TOKEN=[R]
      - PREFIX=,
      - OWNER=[R]
      - TZ=[R]
      - PUID=1000

```

**Environment info:**
Ubuntu Server 22.04.3 LTS

**Additional context**
These are the logs (nothing), I don't know what could be happening, maybe it is something I don't understand and it isn't an issue (sorry in advance if that's the case, researched some documentation but couldn't get it working)

>Starting Red-DiscordBot!
> [INFO] discord.client: logging in using static token
> [INFO] red: No packages were loaded.
> [INFO] discord.gateway: Shard ID 0 has connected to Gateway (Session ID: REDACTED).
> [INFO] red: Connected to Discord. Getting ready...
> [RED DISCORD LOGO]
 ╭────────── nothing ──────────╮ ╭─────────────────────╮
 │  Prefixes           │ ,      │ │  Shards       │ 1   │
 │  Language           │ en-US  │ │  Servers      │ 1   │
 │  Red version        │ 3.5.3  │ │  Unique Users │ 59  │
 │  Discord.py version │ 2.3.1  │ ╰─────────────────────╯
 │  Storage type       │ JSON   │                        
 ╰──────────────────────────────╯                        
> Loaded 2 cogs with 41 commands
> 
