### ISSUE TITLE
Included network tools for health monitoring

### ISSUE THREAD

**Issue by r-vd-woude** [PhasecoreX/docker-red-discordbot#88]
Hello, thanks for the awesome container, use it almost daily!

I was wondering if you could include a package like "curl" or "netcat" in the image?
That way we can write a healthcheck to start the container up again when it loses connectivity.
I'm using the container with the network_mode being another container, so if that container restarts, Red will loose connectivity, and not restart. 
With something like "curl", we could included a simple healthcheck like "curl -sf https://example.com  || exit 1" and restart the container.

I know it is probably a niche cace.

**Comment by PhasecoreX** [comment]
Can you use something like what I did for the dashboard image instead of curl/wget/netcat?

https://github.com/PhasecoreX/docker-red-dashboard/blob/f1fbf74177c792e9fa0d5bb660f91561fd83920d/Dockerfile#L14

I don't really want to add more stuff to the image unless Redbot itself is actually using it.

**Comment by r-vd-woude** [comment]
@PhasecoreX 
Thank you, that worked!
For future reference (if other people need this), this is what I added in my compose file:

```
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/1.1.1.1/53"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
```
