### ISSUE TITLE
Track Error; Something went wrong decoding the track. (OpenJDK11)

### ISSUE THREAD

**Issue by FaNt4zMa** [PhasecoreX/docker-red-discordbot#92]
**Describe the bug**
Pretty often I get an error saying something went wrong decoding the track. I'd say 50% of songs I'd play would just stop randomly. So it got me thinking, maybe it has to do with the java version itself because, on Red's website, they recommend openjdk17-jre and I see that the dockerfile installs openjdk11... I'm pretty novice with docker still and don't know how to modify a dockerfile and build my own container, so if you could update the dockerfile to install 17, that would be very nice and maybe fix the problem :)

**Run command**
```
services:
    red-discordbot:
       image: phasecorex/red-discordbot
       container_name: red-discordbot
       env_file: stack.env
       environment:
            - TOKEN=$TOKEN
            - OWNER=$OWNER
            - PREFIX=$PREFIX
            - TZ=$TZ
            - PUID=$PUID
       volumes:
            - /home/fantaz/Tools/Red Discord Bot/data:/data
       restart: unless-stopped
```

**Environment info:**
OS: linux x86_64 Ubuntu 22.04.4 LTS
Kernel: 5.15.0-113-generic
Docker Version: 27.0.3
Portainer Version: 2.20.3
CPU: i3 380M 2.53GHz
RAM: 4GB DDR3 1067MHz

**Additional context**
![Screenshot 2024-07-03 155152](https://github.com/PhasecoreX/docker-red-discordbot/assets/17235669/7efc1d57-02f2-41f2-80eb-7968aac924bd)
